config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'movies#index'
  resources :movies, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'search'
      get 'finely'
    end
  end
  resources :genres, only: [:index, :new, :create]
  resources :ends, only: [:new, :create]
  resources :eras, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/end.rb
class End < ApplicationRecord
  has_many :movies, through: :end_movies
  has_many :end_movies
end

app/models/end_movie.rb
class EndMovie < ApplicationRecord
  belongs_to :end
  belongs_to :movie
end

app/models/era.rb
class Era < ApplicationRecord
  has_many :movies, through: :era_movies
  has_many :era_movies
end

app/models/era_movie.rb
class EraMovie < ApplicationRecord
  belongs_to :era
  belongs_to :movie
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  has_many :users
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies, through: :genre_movies
  has_many :genre_movies
end

app/models/genre_movie.rb
class GenreMovie < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :genres, through: :genre_movies
  has_many :genre_movies
  has_many :ends, through: :end_movies
  has_many :end_movies
  has_many :eras, through: :era_movies
  has_many :era_movies
  has_many :evaluations

  accepts_nested_attributes_for :evaluations
  accepts_nested_attributes_for :genre_movies
  accepts_nested_attributes_for :end_movies
  accepts_nested_attributes_for :era_movies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :evaluations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ends_controller.rb
class EndsController < ApplicationController
  before_action :redirect

  def new
    @end = End.new
  end
  def create
    redirect_to action: :new if End.create(end_params)
  end

  private
  def end_params
    params.require(:end).permit(:attribute_end)
  end 
  def redirect
    redirect_to root_path unless current_user.id == 1
  end
end

app/controllers/eras_controller.rb
class ErasController < ApplicationController
  before_action :redirect

  def new
    @era = Era.new
  end
  def create
    redirect_to action: :new if Era.create(era_params)
  end

  private
  def era_params
    params.require(:era).permit(:attribute_era)
  end
  def redirect
    redirect_to root_path unless current_user.id == 1
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :redirect, only: [:new, :create]

  def index
    @genres = Genre.all
  end
  
  def new
    @genre = Genre.new
  end
  def create
    redirect_to action: :new if Genre.create(genre_params)
  end

  private
  def genre_params
    params.require(:genre).permit(:attribute_genre)
  end
  def redirect
    redirect_to root_path unless current_user.id == 1
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :redirect, only: [:new, :create]

  def index
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      movies, @movies = @genre.genre_movies.all, []
      movies.each do |movie|
        @movies.push(movie.movie)
      end
    else
      @movies = Movie.all
      recommended_movies if user_signed_in?
    end
  end

  def new
    @movie = Movie.new
    @genres, @ends, @eras = Genre.all, End.all, Era.all
  end

  def create
    redirect_to new_movie_path if Movie.create(movie_params)
  end

  def edit
    @movie = Movie.find(params[:id])
    @genres, @ends, @eras = Genre.all, End.all, Era.all
    if @evaluation = Evaluation.where(user_id: current_user.id).find_by(movie_id: params[:id])
    else
      @evaluation = @movie.evaluations.new
    end
  end

  def update
    movie = Movie.find(params[:id])
    if evaluation = movie.evaluations.find_by(user_id: current_user.id)
      evaluation.delete
    end
    if current_user.id == 1 && movie.update(movie_params)
      redirect_to edit_movie_path
    elsif movie.update(movie_params)
      redirect_to root_path 
    else
      render :edit
    end
  end

  def search
  end

  def finely
    @movies = Movie.all
    if params[:genre_ids]
      movies_genre, movies_era, movies = [], [], []
      attributes = ["genre", "era"]
      attributes.each do |string|
        eval(
        "params[:#{string}_ids].each do |id|
          nums = #{string.capitalize}Movie.all.includes(:#{string}, :movie)
          nums.where(#{string}_id: id.to_i).each do |num|
            movies_#{string}.push(@movies.find(num.movie_id))
          end
        end")
      end
      @movies.each do |movie|
        movies.push(movie) if movies_genre.include?(movie) && movies_era.include?(movie)
      end
      @movies = movies
    end
  end

  private
  def movie_params
    params.require(:movie).permit(:name, :details, evaluations_attributes: [:value, :user_id],
    genre_movies_attributes: [:genre_id], end_movies_attributes: [:end_id], era_movies_attributes: [:era_id]) 
  end

  def redirect
    redirect_to root_path unless current_user.id == 1
  end

  def recommended_movies
    @movies.each do |movie|
      movie.evaluations.where(user_id: current_user.id).each do |evaluation|
        eval(
        "@movie#{movie.id}_eva = evaluation.value")
      end
    end

    Genre.all.length.times do |n|
      genre_point, i = 3, 1
      Genre.find(n + 1).genre_movies.each do |middle|
        if eval("@movie#{middle.movie_id}_eva") != nil
          genre_point += eval("@movie#{middle.movie_id}_eva")
          i += 1
        end
      end
      genre_point /= i
      Genre.find(n + 1).update(point_genre: genre_point)
    end
    End.all.length.times do |n|
      end_point, i = 3, 1
      End.find(n + 1).end_movies.each do |middle|
        if eval("@movie#{middle.movie_id}_eva") != nil
          end_point += eval("@movie#{middle.movie_id}_eva")
          i += 1
        end
      end
      end_point /= i
      End.find(n + 1).update(point_end: end_point)
    end
    Era.all.length.times do |n|
      era_point, i = 3, 1
      Era.find(n + 1).era_movies.each do |middle|
        if eval("@movie#{middle.movie_id}_eva") != nil
          era_point += eval("@movie#{middle.movie_id}_eva")
          i += 1
        end
      end
      era_point /= i
      Era.find(n + 1).update(point_era: era_point)
    end

    @movies.each do |movie|
      temp_point, i = 3, 1
      attributes = ["genre", "end", "era"]
      attributes.each do |string|
        eval(
        "movie.#{string}_movies.each do |middle|
          temp_point += middle.#{string}.point_#{string}
          i += 1
        end")
      end
      temp_point /= i
      movie.update(point_temp: temp_point)
    end
    @movies = @movies.order(point_temp: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ends_helper.rb
module EndsHelper
end

app/helpers/eras_helper.rb
module ErasHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/ends/new.html.haml
= form_with(model: @end, local: true) do |f|
  = f.text_field :attribute_end, placeholder: 'attribute'
  = f.submit 'SEND'

app/views/eras/new.html.haml
= form_with(model: @era, local: true) do |f|
  = f.text_field :attribute_era, placeholder: 'attribute'
  = f.submit 'SEND'

app/views/genres/index.html.haml
- @genres.each do |genre|
  = link_to movies_path(genre_id: genre.id) do
    = genre.attribute_genre

app/views/genres/new.html.haml
= form_with(model: @genre, local: true) do |f|
  = f.text_field :attribute_genre, placeholder: 'attribute'
  = f.submit 'SEND'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MoviesApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/movies/_list.html.haml
- @genres.each do |genre|
  = genre.id
  = genre.attribute_genre
- @ends.each do |end_|
  = end_.id
  = end_.attribute_end
- @eras.each do |era|
  = era.id
  = era.attribute_era

app/views/movies/edit.html.haml
= form_with(model: @movie, local: true) do |f|
  = f.fields_for :evaluations, @evaluation do |e|
    = e.number_field :value, placeholder: 'evaluation'
    = e.number_field :user_id, value: "#{current_user.id}"
  = f.submit 'SEND'

- if current_user.id == 1
  = form_with(model: @movie, local: true) do |f|
    = f.fields_for :genre_movies, @movie.genre_movies.new do |a|
      = a.number_field :genre_id, placeholder: 'genre'
    = f.submit 'SEND'
  = form_with(model: @movie, local: true) do |f|
    = f.fields_for :end_movies, @movie.end_movies.new do |a|
      = a.number_field :end_id, placeholder: 'end'
    = f.submit 'SEND'
  = form_with(model: @movie, local: true) do |f|
    = f.fields_for :era_movies, @movie.era_movies.new do |a|
      = a.number_field :era_id, placeholder: 'era'
    = f.submit 'SEND'
  %br/
  = render partial: 'list'

app/views/movies/finely.html.haml
= form_with(url: finely_movies_path, local: true, method: :get) do |f|
  = f.collection_check_boxes :genre_ids, Genre.all, :id, :attribute_genre
  = f.collection_check_boxes :era_ids, Era.all, :id, :attribute_era
  = f.submit 'SEND'

- @movies.each do |movie|
  = movie.name
  = link_to '評価', edit_movie_path(movie.id)

app/views/movies/index.html.haml
- if current_user && current_user.id == 1
  = link_to '映画登録', new_movie_path
  = link_to 'ジャンル登録', new_genre_path
  = link_to 'エンド登録', new_end_path
  = link_to '時代登録', new_era_path

%br/
- if user_signed_in?
  - @movies.each do |movie|
    = movie.name
    = link_to '評価', edit_movie_path(movie.id)
  %br/
  = link_to '検索', search_movies_path
  = link_to 'ログアウト', destroy_user_session_path, method: :delete
- else
  = link_to '新規登録', new_user_registration_path
  = link_to 'ログイン', new_user_session_path

app/views/movies/new.html.haml
= form_with(model: @movie, local: true) do |f|
  = f.text_field :name, placeholder: 'name'
  = f.text_area :details, placeholder: 'details'
  = f.fields_for :genre_movies, @movie.genre_movies.new do |a|
    = a.number_field :genre_id, placeholder: 'genre'
  = f.fields_for :end_movies, @movie.end_movies.new do |a|
    = a.number_field :end_id, placeholder: 'end'
  = f.fields_for :era_movies, @movie.era_movies.new do |a|
    = a.number_field :era_id, placeholder: 'era'
  = f.submit 'SEND'
  %br/
  = render partial: 'list'

app/views/movies/search.html.haml
= link_to 'ジャンルから探す', genres_path
= link_to '詳細情報で絞り込む', finely_movies_path